from .businessstandard import *
from .businesstoday import *
from .economictimes import *
from .financialexpress import *
from .firstpost import *
from .freepressjournal import *
from .indianexpress import *
from .moneycontrol import *
from .ndtvprofit import *
from .news18 import *
from .outlookindia import *
from .thehindu import *
from .thehindubusinessline import *
from .zeenews import *
from .cnbctv18 import *